<a href="https://colab.research.google.com/github/S1ink/Colabs/blob/main/testing/TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Tensors**

In [9]:
import tensorflow as tf
import numpy as np

x = tf.constant(
    [
        [1., 2, 3],
        [4, 5, 6]
    ]
)

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [6]:
print(x + x)
print(5 * x)
print(x @ tf.transpose(x))
print(tf.concat([x, x, x], axis=0))
print(tf.nn.softmax(x, axis = -1))
print(tf.reduce_sum(x))

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 5. 10. 15.]
 [20. 25. 30.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]], shape=(6, 3), dtype=float32)
tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]], shape=(2, 3), dtype=float32)
tf.Tensor(21.0, shape=(), dtype=float32)


In [8]:
a = [1, 2, 3]
print(a)
print(tf.convert_to_tensor(a))
print(tf.reduce_sum(a))

[1, 2, 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [2]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [29]:
r1 = tf.constant(4)
print(r1)

r2 = tf.constant([2, 3, 4], dtype=tf.float64)
print(r2)

r3 = tf.constant(
    [
        [1, 2, 3, 0],
        [6., 7., 8., 5.89808]
    ]
)
print(r3)

print(np.array(r3) == r3.numpy())

print(tf.add(r2, [3, 4, 9]))
print(tf.matmul([[1], [2], [3]], [[1, 2, 3]]))

print(tf.math.argmax(r3[0]))
print(tf.reduce_max(r2))

print(r3.shape)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float64)
tf.Tensor(
[[1.      2.      3.      0.     ]
 [6.      7.      8.      5.89808]], shape=(2, 4), dtype=float32)
[[ True  True  True  True]
 [ True  True  True  True]]
tf.Tensor([ 5.  7. 13.], shape=(3,), dtype=float64)
tf.Tensor(
[[1 2 3]
 [2 4 6]
 [3 6 9]], shape=(3, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(4.0, shape=(), dtype=float64)
(2, 4)


In [30]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

[ 0  1  1  2  3  5  8 13 21 34]
First: 0
Second: 1
Last: 34
Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [34]:
rank_2_tensor = tf.constant(
    [
        [7, 8, 4, 2, 3],
        [0, 3, 5, 6, 1],
        [7, 6, 5, 1, 3]
    ]
)

print(rank_2_tensor.numpy())

# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

print(rank_2_tensor[:, :].numpy())

[[7 8 4 2 3]
 [0 3 5 6 1]
 [7 6 5 1 3]]
3
Second row: [0 3 5 6 1]
Second column: [8 3 6]
Last row: [7 6 5 1 3]
First item in last column: 3
Skip the first row:
[[0 3 5 6 1]
 [7 6 5 1 3]] 

[[7 8 4 2 3]
 [0 3 5 6 1]
 [7 6 5 1 3]]


In [42]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
print(x.shape)

# You can convert this object into a Python list, too
print(x.shape.as_list())

# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])
print(x.shape)
print(reshaped.shape)

print(x.numpy())
print(reshaped.numpy())

def flatten(t):
    return tf.reshape(t, [-1])

print(flatten(x).numpy())

(3, 1)
[3, 1]
(3, 1)
(1, 3)
[[1]
 [2]
 [3]]
[[1 2 3]]
[1 2 3]


In [43]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


In [46]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

# These are the same computations
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [53]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]
print(ragged_list)

try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ragged_tensor = tf.ragged.constant(ragged_list, dtype=tf.float64)
print(ragged_tensor)
print(ragged_tensor.shape)

[[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]
ValueError: Can't convert non-rectangular Python sequence to Tensor.
<tf.RaggedTensor [[0.0, 1.0, 2.0, 3.0], [4.0, 5.0], [6.0, 7.0, 8.0], [9.0]]>
(4, None)


In [55]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                         values=[1, 2],
                                         dense_shape=[3, 4])

print(sparse_tensor, "\n")
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


#**Variables**

In [56]:
import tensorflow as tf
import numpy as np

tf.debugging.set_log_device_placement(True)

In [60]:
my_tensor = tf.constant([[1, 3], [9, 8]], dtype=tf.float64)
my_variable = tf.Variable(my_tensor)

bool_variable = tf.Variable([False, True, True, True])
complex_variable = tf.Variable([4 + 7j, 6 - 8j])

print(my_variable)
print(bool_variable)
print(complex_variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float64, numpy=
array([[1., 3.],
       [9., 8.]])>
<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False,  True,  True,  True])>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([4.+7.j, 6.-8.j])>


In [61]:
a = tf.Variable([])
a.assign([1, 2, 3, 4])


ValueError: ignored

#**Gradients and Differentiation**

In [62]:
import tensorflow as tf
import numpy as np

In [63]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
  y = x**2

dy_dx = tape.gradient(y, x)
print(x, '\n', y, '\n', dy_dx.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0> 
 tf.Tensor(9.0, shape=(), dtype=float32) 
 6.0


In [66]:
w = tf.Variable(tf.random.normal((3, 2), name='w'))
b = tf.Variable(tf.zeros(2, dtype=tf.float32), name='b')
x = [[2., 5, 6]]

with tf.GradientTape(persistent=True) as tape:
  y = x @ w + b
  loss = tf.reduce_mean(y**2)

print(y, "\n", loss)

[dl_dw, dl_db] = tape.gradient(loss, [w, b])
print(dl_dw, "\n", dl_db)

tf.Tensor([[0.8235357 8.025144 ]], shape=(1, 2), dtype=float32) 
 tf.Tensor(32.54057, shape=(), dtype=float32)
tf.Tensor(
[[ 1.6470714 16.050287 ]
 [ 4.1176786 40.125717 ]
 [ 4.941214  48.150864 ]], shape=(3, 2), dtype=float32) 
 tf.Tensor([0.8235357 8.025144 ], shape=(2,), dtype=float32)


In [67]:
vars = {
    'w' : w,
    'b' : b
}
grad = tape.gradient(loss, vars)
print(grad['b'])

tf.Tensor([0.8235357 8.025144 ], shape=(2,), dtype=float32)
